name: Create a comment on new issue
on:
  issues:
    types:
      - opened
jobs:
  comment_with_action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump GitHub context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash